WITH FIRST_GEN AS (
    SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL
),
SEC_GEN AS (
    SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT * FROM FIRST_GEN)
)

SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT * FROM SEC_GEN) ORDER BY ID