-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE * SUM(OS.SALES_AMOUNT) AS SALES
    FROM OFFLINE_SALE OS
    RIGHT JOIN PRODUCT P ON P.PRODUCT_ID = OS.PRODUCT_ID
    GROUP BY 1
    ORDER BY SALES DESC, P.PRODUCT_CODE;