WITH TBL AS (
SELECT 
    ID,
    NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) 'GROUP_NUM' 
FROM ECOLI_DATA
ORDER BY ID
)
SELECT 
    ID,
    CASE 
        WHEN GROUP_NUM = 1 THEN 'LOW'
        WHEN GROUP_NUM = 2 THEN 'MEDIUM'
        WHEN GROUP_NUM = 3 THEN 'HIGH'
    ELSE 'CRITICAL' 
    END AS 'COLONY_NAME'
FROM TBL
