SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    UI.GENDER,
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM
    ONLINE_SALE OS
LEFT JOIN
    USER_INFO UI ON UI.USER_ID = OS.USER_ID
WHERE
    UI.GENDER IS NOT NULL
GROUP BY
    1,2,3
ORDER BY
    1,2,3;
    