-- 코드를 입력하세요
WITH ISRENTAL AS (
    SELECT CAR_ID, SUM(IF(START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16', 1, 0)) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)

SELECT 
    CAR_ID,
    IF(CNT > 0, '대여중', '대여 가능') AS AVAILABILITY
    FROM ISRENTAL
    GROUP BY 1
    ORDER BY 1 DESC