SELECT F.FLAVOR
    FROM FIRST_HALF F
    JOIN (
        SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY J
        GROUP BY 1
    ) J
    ON J.FLAVOR = F.FLAVOR
    ORDER BY J.TOTAL_ORDER + F.TOTAL_ORDER DESC
    LIMIT 3;