WITH ID_WITH_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_MEMBER AS (
    SELECT MEMBER_ID FROM ID_WITH_COUNT c
    WHERE c.CNT = (SELECT MAX(CNT) FROM ID_WITH_COUNT)
)
SELECT 
    DISTINCT P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM 
    MEMBER_PROFILE P
JOIN
    REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE 
    P.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_MEMBER)
ORDER BY
    REVIEW_DATE, R.REVIEW_TEXT