WITH CUI AS (
    SELECT it.ITEM_ID
    FROM ITEM_TREE it
    JOIN ITEM_INFO ii
        ON it.PARENT_ITEM_ID = ii.ITEM_ID
    WHERE it.PARENT_ITEM_ID IS NOT NULL AND ii.RARITY = 'RARE'
)
SELECT 
    ITEM_ID, ITEM_NAME, RARITY
FROM 
    ITEM_INFO
WHERE 
    ITEM_ID IN (SELECT ITEM_ID FROM CUI)
ORDER BY 1 DESC