WITH SUM_GRADE AS (
    SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
)

SELECT SUM(SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
    FROM HR_GRADE HG
    JOIN HR_EMPLOYEES HE ON HE.EMP_NO = HG.EMP_NO
    GROUP BY HG.EMP_NO
    HAVING SCORE = (SELECT MAX(SUM_SCORE) FROM SUM_GRADE)